language: go
sudo: required
go:
  - 1.11.1
  - master
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.11.1
    - IMAGE_NAME=tsuru/gandalf
addons:
  apt:
    packages:
      - rsyslog
      - python
before_script:
  - rsyslogd &
script:
  - make test
  - ./check-fmt.sh
  - go build -o build/gandalf-webserver -ldflags "-linkmode external -extldflags -static" webserver/main.go
  - go build -o build/gandalf-ssh -ldflags "-linkmode external -extldflags -static" bin/gandalf.go
  - python -m pip install --user virtualenv
  - virtualenv -p python2 venv
  - source venv/bin/activate && make doc
services:
  - docker
  - mongodb
matrix:
  allow_failures:
    - go: master
after_success:
  - curl https://raw.githubusercontent.com/tsuru/push-to-docker/master/push.sh | bash
